name: Release CI

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    name: release build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: apk
            arch: x86_64

          - os: ubuntu-latest
            target: aab
            arch: x86_64

          - os: macos-latest
            target: x86_64_dmg
            arch: x86_64

          - os: macos-14
            target: arm64_dmg
            arch: arm64

          - os: windows-latest
            target: x86_64_exe
            arch: x86_64

          - os: ubuntu-latest
            target: x86_64_deb
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: Caij/pure-music
          ref: ${{github.ref_name}}
          token: ${{secrets.GLOBAL_GITHUB_TOKEN}}

      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apk on ubuntu
        if: matrix.target == 'apk'
        run: |
          ./gradlew app:assembleChinaRelease

      - name: Build aab on ubuntu
        if: matrix.target == 'aab'
        run: |
          ./gradlew app:bundleGoogleRelease

      - uses: actions/upload-artifact@v3
        if: matrix.target == 'aab'
        with:
          name: artifacts-${{ matrix.target }}
          path: |
            ${{github.workspace}}/app/build/outputs/bundle/googleRelease/app-google-release.aab

      - name: Build x86_64 dmg on mac
        if: matrix.os == 'macos-latest'
        run: |
          ./gradlew desktopApp:packageReleaseDmg
          uname -m

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: artifacts-${{ matrix.target }}
          if-no-files-found: error
          path: |
            ${{github.workspace}}/desktopApp/build/compose/binaries/main-release/dmg/*.dmg

      - name: Build arm64 dmg on mac
        if: matrix.os == 'macos-14'
        run: |
          ./gradlew desktopApp:packageReleaseDmg
          uname -m

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-14'
        with:
          name: artifacts-${{ matrix.target }}
          if-no-files-found: error
          path: |
            ${{github.workspace}}/desktopApp/build/compose/binaries/main-release/dmg/*.dmg

      - name: Build exe on window
        if: matrix.target == 'x86_64_exe'
        run: |
          ./gradlew desktopApp:packageReleaseExe

      - uses: actions/upload-artifact@v3
        if: matrix.target == 'x86_64_exe'
        with:
          name: artifacts-${{ matrix.target }}
          if-no-files-found: error
          path: |
            ${{github.workspace}}\desktopApp\build\compose\binaries\main-release\exe\*.exe

      - name: Build deb on ubuntu
        if: matrix.target == 'x86_64_deb'
        run: |
          ./gradlew desktopApp:packageReleaseDeb
          ls -a ${{github.workspace}}/desktopApp/build/compose/binaries/main-release/deb
          uname -m

      - uses: actions/upload-artifact@v3
        if: matrix.target == 'x86_64_deb'
        with:
          name: artifacts-${{ matrix.target }}
          if-no-files-found: error
          path: |
            ${{github.workspace}}/desktopApp/build/compose/binaries/main-release/deb/*.deb

      - name: set up JDK 8
        if: matrix.target == 'apk'
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Upload mapping
        if: matrix.target == 'apk'
        run: |
          . ${{github.workspace}}/version.properties
          echo $showVersionName
          cat ${{github.workspace}}/version.properties
          java -jar ${{github.workspace}}/app/buglyqq-upload-symbol.jar -appid 1a1daf5790 -appkey ${{secrets.BUGLY_APP_KEY}} -bundleid com.caij.puremusic -version $showVersionName -platform Android -inputMapping ${{github.workspace}}/app/build/outputs/mapping/chinaRelease/mapping.txt
          gzip -c ${{github.workspace}}/app/build/outputs/mapping/chinaRelease/mapping.txt > ${{github.workspace}}/app/build/outputs/mapping/chinaRelease/mapping.txt.gz
          curl -F "chat_id=-1002062702442" -F "caption=$showVersionName" -F document=@${{github.workspace}}/app/build/outputs/mapping/chinaRelease/mapping.txt.gz -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument"

      - uses: actions/upload-artifact@v3
        if: matrix.target == 'apk'
        with:
          name: artifacts-${{ matrix.target }}
          if-no-files-found: error
          path: |
            ${{github.workspace}}/app/build/outputs/apk/china/release/app-china-release.apk 

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Caij/pure-music
          ref: ${{github.ref_name}}
          token: ${{secrets.GLOBAL_GITHUB_TOKEN}}

      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Query version number
        run: |
          . ${{github.workspace}}/version.properties
          echo $versionName
          lastVersionName=$versionName
          echo $lastVersionName
          echo "version=$lastVersionName" >> $GITHUB_ENV
          cat ${{github.workspace}}/version.properties

      - name: Download x86_64 dmg artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts-x86_64_dmg
          path: artifacts/x86_64_dmg

      - name: Download amr64 dmg artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts-arm64_dmg
          path: artifacts/arm64_dmg

      - name: Download apk artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts-apk
          path: artifacts/apk

      #      - name: Download aab artifacts
      #        uses: actions/download-artifact@v3
      #        with:
      #          name: artifacts-aab
      #          path: artifacts/aab

      - name: Download exe artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts-x86_64_exe
          path: artifacts/x86_64_exe

      - name: Download deb artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts-x86_64_deb
          path: artifacts/x86_64_deb

      - name: Rename artifacts
        run: |
          mv "artifacts/x86_64_dmg/PureMusic-${{ env.version }}.dmg" "artifacts/PureMusic_${{ github.ref_name }}_macos_x86_64.dmg"
          mv "artifacts/arm64_dmg/PureMusic-${{ env.version }}.dmg" "artifacts/PureMusic_${{ github.ref_name }}_macos_arm64.dmg"
          mv "artifacts/x86_64_exe/PureMusic-${{ env.version }}.exe" "artifacts/PureMusic_${{ github.ref_name }}_windows_x86_64.exe"
          mv "artifacts/x86_64_deb/com.caij.puremusic.linux_${{ env.version }}_amd64.deb" "artifacts/PureMusic_${{ github.ref_name }}_linux_x86_64.deb"
          ls -a artifacts/apk
      #          mv "artifacts/aab/app-google-release.aab" "artifacts/PureMusic_${{ github.ref_name }}_android.aab"

      - name: Build channel apk
        run: |
          mkdir -p "${{github.workspace}}/app/channel"
          mv "artifacts/apk/app-china-release.apk" "${{github.workspace}}/app/channel/PureMusic_${{ github.ref_name }}.apk"
          java -jar ${{github.workspace}}/app/VasDolly.jar put -c "github,telegram,xiaomi,huawei,kuan,qq,lanzou" ${{github.workspace}}/app/channel/PureMusic_${{ github.ref_name }}.apk ${{github.workspace}}/app/channel
          mv "${{github.workspace}}/app/channel/github-PureMusic_${{ github.ref_name }}.apk" "artifacts/apk/PureMusic_${{ github.ref_name }}_android.apk"

      - name: Create Release
        id: create_remote_release
        uses: softprops/action-gh-release@v1
        env:
          PRERELEASE: ${{ contains(github.ref_name, 'beta') ||  contains(github.ref_name, 'rc')}}
        with:
          tag_name: ${{github.ref_name}}
          name: ${{github.ref_name}}
          body_path: ${{ github.workspace }}/CHANGELOG.txt
          files: ./artifacts/**/*
          prerelease: ${{env.PRERELEASE}}

      - name: Read CHANGELOG
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ${{ github.workspace }}/CHANGELOG.txt

      - name: send tg message
        run: |
          curl -F "chat_id=-1001816793644" -F "caption=${{steps.read_file.outputs.contents}}${{steps.create_remote_release.outputs.url}}" -F document=@${{github.workspace}}/app/channel/telegram-PureMusic_${{ github.ref_name }}.apk -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument"

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-channel-apk
          path: |
            ${{github.workspace}}/app/channel/*.apk

      - name: upload lanzou
        if: ${{ !contains(github.ref_name, 'beta') && !contains(github.ref_name, 'rc')}}
        run: |
          curl --location --request PUT '${{ secrets.ALIST_HOST }}/api/fs/form' \
          --header 'Authorization: ${{ secrets.ALIST_TOKEN }}' \
          --header 'File-Path: /puremusic/lanzou-PureMusic_${{ github.ref_name }}.apk' \
          --header 'As-Task: true' \
          --header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
          --form 'file=@"${{github.workspace}}/app/channel/lanzou-PureMusic_${{ github.ref_name }}.apk"'
#      - name: send tg message
#        uses: appleboy/telegram-action@master
#        with:
#          to: -1001816793644
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: "${{steps.read_file.outputs.contents}}"
#          document: ${{github.workspace}}/artifacts/PureMusic_${{ env.version }}_android.apk