name: Release CI

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    name: release build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: apk
            arch: x86_64
          - os: ubuntu-latest
            arch: x86_64
            target: aab
          - os: macos-latest
            arch: x86_64
            target: x86_dmg

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: Caij/pure-music
          ref: ${{github.ref_name}}
          token: ${{secrets.GLOBAL_GITHUB_TOKEN}}

      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Build apk on ubuntu
#        if: matrix.target == 'apk'
#        run: |
#          ./gradlew app:assembleChinaRelease

#      - uses: actions/upload-artifact@v3
#        if: matrix.target == 'apk'
#        with:
#          name: artifacts-${{ matrix.target }}
#          path: |
#            ${{github.workspace}}/app/build/outputs/apk/china/release/app-china-release.apk
#
#      - name: Build aab on ubuntu
#        if: matrix.target == 'aab'
#        run: |
#          ./gradlew app:bundleGoogleRelease
#
#      - uses: actions/upload-artifact@v3
#        if: matrix.target == 'aab'
#        with:
#          name: artifacts-${{ matrix.target }}
#          path: |
#            ${{github.workspace}}/app/build/outputs/bundle/googleRelease/app-google-release.aab

      - name: Build dmg on mac
        if: matrix.os == 'macos-latest'
        run: |
          ./gradlew desktopApp:packageReleaseDmg

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: artifacts-${{ matrix.target }}
          path: |
            ${{github.workspace}}/desktopApp/build/compose/binaries/main-release/dmg/*.dmg
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
        run: echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Download x86_64 dmg artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts-x86_dmg
          path: artifacts/x86_dmg

      - name: Rename artifacts
        run: |
          mv "artifacts/x86_dmg/PureMusic-${{ env.version }}.dmg" "artifacts/PureMusic_${{ env.version }}_inter.dmg"

      - name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          name: ${{github.ref_name}}
          body_path: ${{ github.workspace }}/CHANGELOG.txt
          files: ./artifacts/**/*